### ISSUE TITLE
[FR] Display workspaces as names or icons instead of digits

### ISSUE THREAD

**Issue by edgar-vincent** [fthx/workspaces-bar#1]
Hi!

Thanks a lot for this excellent extension! Do you think it would be possible to use icons (eg. with Font Awesome) and/or names instead of (or as well as) digits as workspace indicators?

Thanks again,

ev

**Comment by fthx** [comment]
Hi,

Using icons will just imho import some issues (license, compatibility, scaling...) but anyway, what icons would you see instead of numbers? Custom icons chosen by user?

For names, I'm aware of this since some time because it's already an user request. I've just found that it could be easy because the workspaces names do already have a dconf key... ;-) 
So I'm working on this right now, I'll post you the candidate version asap.

**Comment by edgar-vincent** [comment]
I don't have much experience with Gnome. I used to use waybar with Sway, which allows one to set the text description of different workspaces as a string in a configuration file - hence allowing one to use the [Awesome font icons](https://fontawesome.com/) and keeping clear of licensing issues upstream. Would that be possible within the Gnome framework?

I also recently noticed that workspaces could be given names, but couldn't see where or even if they were displayed.

Thanks a lot for your reply!

ev

**Comment by fthx** [comment]
Ok, I won't include icons because it's quite a lot of work. ;-)

BUT you can get now workspaces names. :-) 
Get the code in this GitHub repo or:
https://extensions.gnome.org/review/21869
zip file: https://extensions.gnome.org/review/download/21869.shell-extension.zip
(If you are not aware of GNOME stuff, simply just copy/paste the new extension.js code instead of the existing one in ~/.local/share/gnome-shell/extensions/workspaces-bar@fthx then restart your session.)

Workspaces names are taken through GNOME official way. See description header in extension webpage.

**Comment by edgar-vincent** [comment]
It works fine, thanks a lot.
For what it's worth, one can display icons with a patched [Nerd Font](https://www.nerdfonts.com/). It works perfectly with the new version of the extension.

**Comment by edgar-vincent** [comment]
FWIW, here's what it looks like with icons: 
![Screenshot from 2020-12-30 11-09-15](https://user-images.githubusercontent.com/63352906/103344820-fff5a700-4a8f-11eb-986a-68a3d161819b.png)

**Comment by fthx** [comment]
Ok that's nice!
But it would require to make a complete prefs interface for the user to select icons... Maybe one day if I have some time.
